### PR TITLE
Node Coloring Heuristics

### PR DESCRIPTION
**Pull request by milsen**
Implemented by Jan-Niklas Buckow in 2021 for his master's thesis "Approximationsalgorithmen für das Knotenfärbungsproblem in Graphen" (Approximation Algorithms for the Vertex Coloring Problem in Graphs).

Part of #220

### CODE REVIEW

**Comment by N-Coder** [comment]
Looks good to me, I can take care of the button-pressing after one small comment: would it make sense to put all the headers into a separate folder?

**Comment by milsen** [comment]
> Looks good to me, I can take care of the button-pressing after one small comment: would it make sense to put all the headers into a separate folder?

Yes, kind of. The problem is that sometimes a subsubdirectory of `include/ogdf/` is used for a) only internally used code (as is the case in most of the OGDF and was actually kind of a rule at some point), and sometimes for b) more fine-grained categorization (as you are suggesting, partially done in `basic/`). Currently, all files in `graphalg/` conform to a), so I did not want to break that consistency.

However, I do think that in the long run, the current directory structure leads to dirs with way too many files. It should be revised at some point, but "we can do that later" :tm:  :arrow_right:   #167

**Comment by milsen** [comment]
> It seems that the `node-coloring` test is currently [not run](https://github.com/ogdf/ogdf/actions/runs/11131411568/job/30932995892?pr=250), which is why Sonar reports 0% test coverage - maybe tests have to begin with `test`?

Good catch. Well, the binaries all are prefixed by `test` and so is `test-node-coloring`, which apparently [does get compiled](https://github.com/ogdf/ogdf/actions/runs/11131411568/job/30932995892?pr=250#step:6:1227). Weird...

**Comment by milsen** [comment]
> It seems that the `node-coloring` test is currently [not run](https://github.com/ogdf/ogdf/actions/runs/11131411568/job/30932995892?pr=250), which is why Sonar reports 0% test coverage - maybe tests have to begin with `test`?

I may have fixed it by adding a `()` :man_facepalming: .  Maybe for it to count as coverage, you need a `go_bandit([]() {
`, and without `()` it does not count. Let's see.

**Comment by N-Coder** [comment]
The newly-added files are entirely missing from the coverage report (see at the bottom of [this page](https://github.com/ogdf/ogdf/actions/runs/11131411568?pr=250) under artifacts / coverage). So maybe try running the coverage reporting just for this single executable locally and see what happens?
The only issue I can currently think of is that the [PID-based](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#running-the-instrumented-program) [names for raw coverage files](https://github.com/ogdf/ogdf/blob/master/util/test_coverage.sh#L50) collided and the file was overwritten due to PID-reuse, but with [usually sequential PIDs](https://superuser.com/questions/135007/how-are-pids-generated) on multiple tests runs of otherwise non-flaky coverage data, this is pretty unlikely.

**Comment by milsen** [comment]
I think the problem is that all the code is implemented in header files. The functions are probably inlined by the compiler and thus, no actual function call is generated for which coverage could be computed. So I'll move the function definitions to cpp-files (which should be done anyway) and it should work.

**Comment by N-Coder** [comment]
The clang docs state that this should [not be the case](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#impact-of-llvm-optimizations-on-coverage-reports), but it's sure worth a try

**Comment by milsen** [comment]
Wow, it actually worked. Good to keep in mind for the future that inlined function definitions may not be counted...

Anyway, this is now merge-ready!

**Comment by N-Coder** [comment]
Ah, staring a little longer at the script I found the culprit [here](https://github.com/ogdf/ogdf/blob/83f8402cf0333a4e5967996e126ea20a16d415ba/util/test_coverage.sh#L55). The [tool for analyzing coverage measurements](https://llvm.org/docs/CommandGuide/llvm-cov.html) needs to know some binary for which those measurements were made. Because I couldn't list all the separate test executables, I just used `libOGDF.so`. So whatever doesn't land in `libOGDF.so` (i.e., all tests and also all headers that are *only* used from tests) will not be included in the report. This can probably be fixed by compiling all tests into a single executable for this analysis (which is possible by a config option, but will also mean that tests are always run without parallelism - which might be not too bad on the weak CI VMs anyway), but this will probably need more changes to our scripts and will probably still miss the examples...

**Pull request merged**
